# Generated by Django 5.2.16 on 2026-08-10 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='upload/default.png', upload_to='upload/')),
                ('nickname', models.CharField(blank=True, default='', max_length=30, verbose_name='昵称')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('dep', models.CharField(blank=True, choices=[('班子成员', '班子成员'), ('退二线科级干部', '退二线科级干部'), ('办公室', '办公室'), ('党组办公室', '党组办公室'), ('财务股', '财务股'), ('人事股', '人事股'), ('公用事业股', '公用事业股'), ('工会', '工会'), ('行政审批股', '行政审批股'), ('督查大队', '督查大队'), ('监察大队', '监察大队'), ('公车办公室', '公车办公室'), ('环卫大队', '环卫大队'), ('一片区', '一片区'), ('二片区', '二片区'), ('三片区', '三片区'), ('四片区', '四片区'), ('五片区', '五片区'), ('六片区', '六片区'), ('七片区', '七片区'), ('清运大队', '清运大队'), ('油烟办', '油烟办'), ('市政大队', '市政大队'), ('垃圾中转站', '垃圾中转站'), ('污征办', '污征办'), ('管网大队', '管网大队'), ('数字化城管', '数字化城管'), ('垃圾监管办', '垃圾监管办'), ('供水办', '供水办'), ('污水办', '污水办'), ('公厕办', '公厕办'), ('渣土大队', '渣土大队'), ('机扫大队', '机扫大队'), ('广告办', '广告办'), ('燃气办', '燃气办'), ('供热办', '供热办'), ('综合执法局', '综合执法局'), ('市场中心', '市场中心'), ('驻村人员', '驻村人员'), ('乡镇综合执法大队挂职人员', '乡镇综合执法大队挂职人员')], max_length=20, verbose_name='所属科室')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户详情',
                'verbose_name_plural': '用户详情',
            },
        ),
    ]
